### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by wardialer** [wardialer/pretty-hate-machine#1]
- [x] ~~Add [Grunt](http://gruntjs.com/)~~
- [x] ~~Replace [controllers](https://github.com/wardialer/pretty-hate-machine/blob/master/public/js/controllers/) with something "ready-to-go"~~
- [x] ~~Replace [route provider](https://github.com/wardialer/pretty-hate-machine/blob/master/public/js/appRoutes.js) with [state provider](https://github.com/angular-ui/ui-router/wiki)~~
- [x] ~~Error Handling~~
- [x] ~~Add [SASS](https://github.com/sass/node-sass)~~
- [ ] Add [Passport](http://passportjs.org/)
